# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tensor_viewer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TensorViewer(object):
    def setupUi(self, TensorViewer):
        TensorViewer.setObjectName("TensorViewer")
        TensorViewer.resize(890, 658)
        self.centralwidget = QtWidgets.QWidget(TensorViewer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.widget_2 = QtWidgets.QWidget(self.splitter_2)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.slices = ImageDisplay(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slices.sizePolicy().hasHeightForWidth())
        self.slices.setSizePolicy(sizePolicy)
        self.slices.setMinimumSize(QtCore.QSize(400, 0))
        self.slices.setText("")
        self.slices.setObjectName("slices")
        self.verticalLayout_3.addWidget(self.slices)
        self.page_controls = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_controls.sizePolicy().hasHeightForWidth())
        self.page_controls.setSizePolicy(sizePolicy)
        self.page_controls.setObjectName("page_controls")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_controls)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.plot = ImageDisplay(self.page_controls)
        self.plot.setText("")
        self.plot.setObjectName("plot")
        self.horizontalLayout_7.addWidget(self.plot)
        self.verticalLayout_3.addWidget(self.page_controls)
        self.widget = QtWidgets.QWidget(self.splitter_2)
        self.widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(20, 379, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.normalization = QtWidgets.QComboBox(self.groupBox_3)
        self.normalization.setObjectName("normalization")
        self.normalization.addItem("")
        self.normalization.addItem("")
        self.verticalLayout_7.addWidget(self.normalization)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.colormap = QtWidgets.QComboBox(self.groupBox_3)
        self.colormap.setObjectName("colormap")
        self.colormap.addItem("")
        self.colormap.addItem("")
        self.verticalLayout_7.addWidget(self.colormap)
        self.widget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.widget_3)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.v_min = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.v_min.setMaximum(1.0)
        self.v_min.setSingleStep(0.01)
        self.v_min.setObjectName("v_min")
        self.horizontalLayout_4.addWidget(self.v_min)
        self.v_max = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.v_max.setMaximum(1.0)
        self.v_max.setSingleStep(0.01)
        self.v_max.setProperty("value", 1.0)
        self.v_max.setObjectName("v_max")
        self.horizontalLayout_4.addWidget(self.v_max)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.downscale = QtWidgets.QCheckBox(self.widget_3)
        self.downscale.setObjectName("downscale")
        self.verticalLayout_8.addWidget(self.downscale)
        self.live_update_plot = QtWidgets.QCheckBox(self.widget_3)
        self.live_update_plot.setObjectName("live_update_plot")
        self.verticalLayout_8.addWidget(self.live_update_plot)
        self.verticalLayout_7.addWidget(self.widget_3)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.label_4)
        self.tensor_min = QtWidgets.QLineEdit(self.groupBox_2)
        self.tensor_min.setObjectName("tensor_min")
        self.verticalLayout_6.addWidget(self.tensor_min)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.label_5)
        self.tensor_max = QtWidgets.QLineEdit(self.groupBox_2)
        self.tensor_max.setObjectName("tensor_max")
        self.verticalLayout_6.addWidget(self.tensor_max)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.frame_mean = QtWidgets.QLineEdit(self.groupBox)
        self.frame_mean.setObjectName("frame_mean")
        self.verticalLayout_5.addWidget(self.frame_mean)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.frame_min = QtWidgets.QLineEdit(self.groupBox)
        self.frame_min.setObjectName("frame_min")
        self.verticalLayout_5.addWidget(self.frame_min)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.frame_max = QtWidgets.QLineEdit(self.groupBox)
        self.frame_max.setObjectName("frame_max")
        self.verticalLayout_5.addWidget(self.frame_max)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.verticalLayout_2.addWidget(self.splitter_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loading_info_stack = QtWidgets.QStackedWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loading_info_stack.sizePolicy().hasHeightForWidth())
        self.loading_info_stack.setSizePolicy(sizePolicy)
        self.loading_info_stack.setMaximumSize(QtCore.QSize(180, 16777215))
        self.loading_info_stack.setObjectName("loading_info_stack")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.file_info = QtWidgets.QLabel(self.page_3)
        self.file_info.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.file_info.setObjectName("file_info")
        self.horizontalLayout_2.addWidget(self.file_info)
        self.loading_info_stack.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.progress = QtWidgets.QProgressBar(self.page_4)
        self.progress.setMaximumSize(QtCore.QSize(180, 16777215))
        self.progress.setProperty("value", 0)
        self.progress.setObjectName("progress")
        self.verticalLayout.addWidget(self.progress)
        self.loading_info_stack.addWidget(self.page_4)
        self.horizontalLayout.addWidget(self.loading_info_stack)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.previous = QtWidgets.QPushButton(self.widget1)
        self.previous.setMinimumSize(QtCore.QSize(80, 0))
        self.previous.setMaximumSize(QtCore.QSize(80, 16777215))
        self.previous.setObjectName("previous")
        self.horizontalLayout.addWidget(self.previous)
        self.next = QtWidgets.QPushButton(self.widget1)
        self.next.setMinimumSize(QtCore.QSize(80, 0))
        self.next.setMaximumSize(QtCore.QSize(80, 16777215))
        self.next.setObjectName("next")
        self.horizontalLayout.addWidget(self.next)
        self.slice = QtWidgets.QSpinBox(self.widget1)
        self.slice.setMaximum(999999999)
        self.slice.setObjectName("slice")
        self.horizontalLayout.addWidget(self.slice)
        self.verticalLayout_2.addWidget(self.widget1)
        TensorViewer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TensorViewer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 17))
        self.menubar.setObjectName("menubar")
        self.menuOpen = QtWidgets.QMenu(self.menubar)
        self.menuOpen.setObjectName("menuOpen")
        TensorViewer.setMenuBar(self.menubar)
        self.toolBar_2 = QtWidgets.QToolBar(TensorViewer)
        self.toolBar_2.setObjectName("toolBar_2")
        TensorViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionOpen = QtWidgets.QAction(TensorViewer)
        self.actionOpen.setObjectName("actionOpen")
        self.actionRotate = QtWidgets.QAction(TensorViewer)
        self.actionRotate.setObjectName("actionRotate")
        self.actionDetect = QtWidgets.QAction(TensorViewer)
        self.actionDetect.setObjectName("actionDetect")
        self.actionImbibition = QtWidgets.QAction(TensorViewer)
        self.actionImbibition.setObjectName("actionImbibition")
        self.actionSave = QtWidgets.QAction(TensorViewer)
        self.actionSave.setObjectName("actionSave")
        self.actionDisplay_xy_slices = QtWidgets.QAction(TensorViewer)
        self.actionDisplay_xy_slices.setObjectName("actionDisplay_xy_slices")
        self.actionDisplay_xz_slices = QtWidgets.QAction(TensorViewer)
        self.actionDisplay_xz_slices.setObjectName("actionDisplay_xz_slices")
        self.actionDisplay_yz_slices = QtWidgets.QAction(TensorViewer)
        self.actionDisplay_yz_slices.setObjectName("actionDisplay_yz_slices")
        self.actionShow_slices = QtWidgets.QAction(TensorViewer)
        self.actionShow_slices.setObjectName("actionShow_slices")
        self.actionShow_Detected_colum_view = QtWidgets.QAction(TensorViewer)
        self.actionShow_Detected_colum_view.setObjectName("actionShow_Detected_colum_view")
        self.actionShow_columnwise_imbibition_front = QtWidgets.QAction(TensorViewer)
        self.actionShow_columnwise_imbibition_front.setObjectName("actionShow_columnwise_imbibition_front")
        self.actionSlice_tensor = QtWidgets.QAction(TensorViewer)
        self.actionSlice_tensor.setObjectName("actionSlice_tensor")
        self.actionOpen_Tensor = QtWidgets.QAction(TensorViewer)
        self.actionOpen_Tensor.setObjectName("actionOpen_Tensor")
        self.close_all_tensors = QtWidgets.QAction(TensorViewer)
        self.close_all_tensors.setObjectName("close_all_tensors")
        self.menuOpen.addAction(self.actionOpen_Tensor)
        self.menuOpen.addSeparator()
        self.menuOpen.addAction(self.close_all_tensors)
        self.menubar.addAction(self.menuOpen.menuAction())

        self.retranslateUi(TensorViewer)
        self.loading_info_stack.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TensorViewer)

    def retranslateUi(self, TensorViewer):
        _translate = QtCore.QCoreApplication.translate
        TensorViewer.setWindowTitle(_translate("TensorViewer", "Tensor Viewer"))
        self.groupBox_3.setTitle(_translate("TensorViewer", "Display Options"))
        self.label_6.setText(_translate("TensorViewer", "Normalization:"))
        self.normalization.setItemText(0, _translate("TensorViewer", "frame normalization"))
        self.normalization.setItemText(1, _translate("TensorViewer", "tensor normalization"))
        self.label_7.setText(_translate("TensorViewer", "Colormap:"))
        self.colormap.setItemText(0, _translate("TensorViewer", "grayscale"))
        self.colormap.setItemText(1, _translate("TensorViewer", "viridis"))
        self.label_9.setText(_translate("TensorViewer", "Vmin"))
        self.label_8.setText(_translate("TensorViewer", "Vmax"))
        self.downscale.setText(_translate("TensorViewer", "Downscale upon loading"))
        self.live_update_plot.setText(_translate("TensorViewer", "update plot"))
        self.groupBox_2.setTitle(_translate("TensorViewer", "Tensor meta"))
        self.label_4.setText(_translate("TensorViewer", "Tensor Min:"))
        self.label_5.setText(_translate("TensorViewer", "Tensor Max:"))
        self.groupBox.setTitle(_translate("TensorViewer", "Slice Meta"))
        self.label.setText(_translate("TensorViewer", "Frame Mean:"))
        self.label_2.setText(_translate("TensorViewer", "Frame Min:"))
        self.label_3.setText(_translate("TensorViewer", "Frame Max:"))
        self.file_info.setText(_translate("TensorViewer", "No file loaded ..."))
        self.previous.setText(_translate("TensorViewer", "<<"))
        self.next.setText(_translate("TensorViewer", ">>"))
        self.menuOpen.setTitle(_translate("TensorViewer", "Start"))
        self.toolBar_2.setWindowTitle(_translate("TensorViewer", "toolBar_2"))
        self.actionOpen.setText(_translate("TensorViewer", "Open source files"))
        self.actionRotate.setText(_translate("TensorViewer", "Rotate tensor"))
        self.actionDetect.setText(_translate("TensorViewer", "Detect columns"))
        self.actionImbibition.setText(_translate("TensorViewer", "Find imbibition front"))
        self.actionSave.setText(_translate("TensorViewer", "Save current tensor"))
        self.actionDisplay_xy_slices.setText(_translate("TensorViewer", "Display xy slices"))
        self.actionDisplay_xz_slices.setText(_translate("TensorViewer", "Display xz slices"))
        self.actionDisplay_yz_slices.setText(_translate("TensorViewer", "Display yz slices"))
        self.actionShow_slices.setText(_translate("TensorViewer", "Show slices"))
        self.actionShow_Detected_colum_view.setText(_translate("TensorViewer", "Show detected colum view"))
        self.actionShow_columnwise_imbibition_front.setText(_translate("TensorViewer", "Show columnwise imbibition front"))
        self.actionSlice_tensor.setText(_translate("TensorViewer", "Slice tensor"))
        self.actionOpen_Tensor.setText(_translate("TensorViewer", "Open Tensor"))
        self.close_all_tensors.setText(_translate("TensorViewer", "Close all tensors"))

from imagedisplay import ImageDisplay
